Add a repel item for enemy blasts
amethyst/theta-wave pull request #152
Opened 2021-05-17 21:09 UTC by tigleym

This PR introduces a player item that repels incoming enemy projectiles. Note:

2021-05-18 04:52 UTC, cdsupina commented
Right off the bat, I can see that the player's `AttractorComponent` includes the `Blast` category. In the current state of the your branch this means that enemy blasts will either attract to the player or repel away from the player.

This is undesireable behavior because blasts should not attract to the player ever at this point. When the player does not have the `BlastRepeller` item, blasts should just move past the player normally. Only when the player picks up the item should blasts alter their behavior and repel away from the player.

A potential fix for this would be to add another `bool` property to the `AttractData` struct called `is_active` which will allow the functionality of the `AttractorComponent` to be switched on or off. This way the player can start the game with `is_active` for `Blast` set to false and only set to true when the `BlastRepeller` item is picked up.

2021-05-18 05:36 UTC, cdsupina requested changes
Overall this is a very solid start! Let me know if you have any questions about my comments.

Another thing to consider is how this item should be balanced. There shouldn't be a single item that can allow the player to have invulnerability from blast damage. Consider keeping the acceleration of the repel effect very low so that it acts as a light push on blasts to move away from the player. 

See how subtle the effect from the soul item is here: https://youtu.be/0t_cfoHLKFY?t=22

Also keeping the modifier values from this item low allows us to make more items in the future that also use these modifiers and build off of their effects without getting too extreme.

Obviously, we don't need to overthink balancing right now, but let me know what you think of the item having more subtle effects.

2021-05-18 05:36 UTC, cdsupina commented on src/components/motion2d.rs
> +            }
Let's not hardcode values here. Any additional acceleration should be passed in through the `bonus_acceleration` parameter in the function. In this case it should come from the `AtrractData` for the `Blast` category in the `AttractionComponent`.

2021-05-18 05:36 UTC, cdsupina commented on src/resources/modifiers.rs
> +    RepelBlasts(bool),
Modifiers should be very specific in what they do. I also see that in `systems/modifiers.rs` you aren't using the bool value in the enum.

I suggest you remove `RepelBlasts(bool)`, and replace it with `BlastAttractorAcceleration(f32)`, `BlastAttractorRadius(f32)`, `BlastAttractorShouldRepel(bool)`, and `BlastAttractorIsActive(bool)`. These modifiers are much more specific and allow us to easily create more items that can use these modifiers in the future.

2021-05-18 05:36 UTC, cdsupina commented on src/systems/modifiers.rs
> +            }
See above comment about specificity of modifiers.

And take note of how the existing modifiers implemented above in this file use the values from the enum to implement the value from the modifier.

2021-05-18 05:36 UTC, cdsupina commented on src/systems/motion2d.rs
> +                            BlastType::Enemy => {
Good catch! I forgot that we would need to check the type of blast it is.

2021-05-18 05:36 UTC, cdsupina commented on src/data_include/data/item_modifiers.ron
> +        RepelBlasts(false),
See comment below in `resources/modifiers.rs` about specificity of modifiers. This item should contain several new modifiers to describe its effects.

2021-05-18 05:36 UTC, cdsupina commented on src/entities/spaceship.rs
> +            should_repel: false,
Let's initialize the base diameter of the `Blast` attraction to be exactly the width of the players hitbox. This would be a radius of 3. This way you can make a modifier that can increase this radius when acquired.

Similarly the acceleration should be set to 0 and another modifier can increase this to the desired acceleration when the item is acquired.

2021-05-19 01:05 UTC, tigleym commented on src/data_include/data/item_modifiers.ron
> +        BlastAttractorRadius(13.0),
@cdsupina I found the acceleration/radius values need to be larger in order for the player to successfully deflect it (most of the time). If it's too low then the collision event is dispatched too frequently, which I'm not too sure if this is what we want?

2021-05-19 01:07 UTC, tigleym commented
Thanks for the review @cdsupina! I'm starting to get a better grasp of how these modifiers are supposed to work. I had some concerns about my latest commit for this PR, particularly what values for the radius and acceleration we should be using (its difficult to find a good balance for this) and the naming for the new item I added `BlastModifier`

2021-05-19 01:09 UTC, tigleym commented on src/data_include/data/item_modifiers.ron
> +    BlastModifiers: [
I don't have a good name for this item atm.

2021-05-19 01:23 UTC, cdsupina commented on src/data_include/data/item_modifiers.ron
> +        BlastAttractorRadius(13.0),
I think leaving the acceleration at 0.3 and significantly reducing the radius was a good choice for balance!

2021-05-19 01:25 UTC, cdsupina commented on src/data_include/data/item_modifiers.ron
> +    BlastModifiers: [
If you can't think of a sci-fy-y creative name, just choose a descriptive one. Maybe just `Repeller`.

2021-05-19 01:29 UTC, cdsupina approved these changes
Great work! LGTM

2021-05-19 02:01 UTC, merged