Refactor distance function
amethyst/theta-wave pull request #162
Opened 2021-06-25 23:55 UTC by tigleym

2021-06-27 04:15 UTC, cdsupina requested changes
Looks good! One minor change requested.

2021-06-27 04:15 UTC, cdsupina commented on thetawave_lib/src/tools/math.rs
> +pub fn distance(point_a: Vector3<f32>, point_b: Vector3<f32>, is2d: bool) -> f32 {
Let's change `is2d` to snake case to be consistent with variable naming scheme. `is_2d`.

2021-06-28 22:48 UTC, tigleym commented on thetawave_lib/src/tools/math.rs
> +pub fn distance(point_a: Vector3<f32>, point_b: Vector3<f32>, is2d: bool) -> f32 {
Good idea! Done.

2021-06-30 04:21 UTC, cdsupina approved these changes

2021-06-30 04:21 UTC, merged